import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { AboutComponent } from './components/about/about.component';
import { ProductsComponent } from './components/products/products.component';
import { ProductComponent } from './components/product/product.component';
import { SearchResultsComponent } from './components/search-results/search-results.component';
import { WarrantyComponent } from './components/policies/warranty/warranty.component';
import { TermsOfServiceComponent } from './components/policies/terms/terms.component';
import { ShippingComponent } from './components/policies/shipping/shipping.component';
import { ContactComponent } from './components/contact/contact.component';
import { LoginComponent } from './components/login/login.component';
import { SignupComponent } from './components/signup/signup.component';
import { ConfirmComponent } from './components/confirm/confirm.component';
import { ForgotPasswordComponent } from './components/forgot-password/forgot-password.component';
import { ResetPasswordComponent } from './components/reset-password/reset-password.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'acerca', component: AboutComponent },
  { path: 'productos', component: ProductsComponent },
  { path: 'productos/:slug', component: ProductComponent },
  { path: 'buscar', component: SearchResultsComponent },
  { path: 'garantia', component: WarrantyComponent },
  { path: 'envios', component: ShippingComponent },
  { path: 'terminos', component: TermsOfServiceComponent },
  { path: 'contacto', component: ContactComponent },
  { path: 'login', component: LoginComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'confirm', component: ConfirmComponent },
  { path: 'recovery', component: ForgotPasswordComponent },
  { path: 'reset', component: ResetPasswordComponent },
  { path: '**', redirectTo: '' },
];
